//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EisenhowerMatrix.WPF.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EisenhowerMatrixEntities : DbContext
    {
        public EisenhowerMatrixEntities()
            : base("name=EisenhowerMatrixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Quadrant> Quadrants { get; set; }
        public virtual DbSet<MatrixTask> MatrixTasks { get; set; }
    }
}
